# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eab5b0f0c2dd3903dd332544062401d902e2bffc9f1c87c7141a31a473cea2366cf728875f8f8879e4340f8a98698489d9a37fda2e2a7805e7da2ed3bb1cd9b5

test:
  secret_key_base: c6005a25af00ba2be32458d583dbab2d60bcd077af0060dce13d2c8553961f9244a7f5da561010fb3f920c86b9f78a6d4850610183f74cab72c1c5180de8710a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
